# 文件名: config.yml 或 pages-cms.yml (取决于您的项目配置)
# Pages CMS 配置文件 - 定义内容编辑结构
# ----------------------------------------------------

# === 全局媒体配置 ===
media:
  input: src/media
  output: /media

# === 内容定义 ===
content:
  # ----------------------------------------
  # 1. 集合：文档 (docs) - (保持不变)
  # ----------------------------------------
  - name: docs
    label: Documentation
    type: collection
    path: src/docs
    filename: "{primary}.md"
    
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      
    default:
      sort: order
      order: asc
      
    fields:
      - name: title
        label: Title
        type: string
        required: true
        
      - name: description
        label: Description
        type: string
        options: { maxlength: 180 }
        
      - name: order
        label: Order
        type: number
        
      - name: body
        label: Body
        type: rich-text

  # ----------------------------------------
  # 2. 文件：主页 (homepage) - 【关键修正区域】
  # ----------------------------------------
  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    
    fields:
      - name: layout
        type: string
        hidden: true
        default: layouts/base.njk
        
      # 组合字段 1: Promotion
      - name: Promotion
        label: Promotion
        type: object
        # 【修正】为必需字段 url 提供一个初始空值 ""
        default: { text: "", url: "" } 
        fields:
          - name: text
            label: Text
            type: string
            
          - name: url
            label: URL
            type: string
            required: true # 保持必需
            
      # 组合字段 2: Features
      - name: features
        label: Features
        type: object
        # 【修正】为必需字段 title 提供一个初始空值 ""
        default: { icon: "", title: "", description: "" } 
        fields:
          - name: icon
            label: Icon
            type: string
            
          - name: title
            label: Title
            type: string
            required: true # 保持必需
            
          - name: description
            label: Description
            type: string