# .pages.yml
# Pages CMS 核心配置文件

# ====================================================================
# MEDIA: 媒体配置 (保持不变)
# ====================================================================
media:
  - name: images
    label: 图片库
    input: src/assets/images
    output: /assets/images
    categories: [ image ] 
    extensions: [ jpg, jpeg, png, webp, svg ]

  - name: files
    label: 文档与附件
    input: src/assets/files
    output: /assets/files
    categories: [ document, video, compressed ]


# ====================================================================
# COMPONENTS: 可重用组件 (保持不变)
# ====================================================================
components:
  seo:
    label: SEO 元数据
    type: object
    description: 搜索引擎优化所需的标题和描述。
    fields:
      - name: seo_title
        label: SEO 标题
        type: string
        description: 最佳长度为 60-70 个字符。
        required: true
      - name: seo_description
        label: SEO 描述
        type: text
        description: 最佳长度为 150-160 个字符。
        options: { maxlength: 160 }
        
  cta_button:
    label: 行动按钮
    type: object
    fields:
      - name: text
        label: 按钮文本
        type: string
        required: true
      - name: url
        label: 链接地址 (URL)
        type: string
        required: true
        pattern: 
          regex: '^(https?:\/\/|\/|#).*'
          message: '请输入有效的 URL (包含 http/https, / 或 #)'


# ====================================================================
# CONTENT: 内容定义
# --------------------------------------------------------------------
content:
  # ----------------------------------------
  # 1. 集合：博客文章 (Blog Posts) - 【日期格式已修正】
  # ----------------------------------------
  - name: posts
    label: 博客文章
    type: collection
    path: src/posts
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter 
    
    view:
      fields: [ title, date, published ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
        
    fields:
      - name: title
        label: 标题
        type: string
        required: true

      - name: published
        label: 是否发布
        type: boolean
        default: false
        
      - name: date
        label: 发布日期
        type: date
        required: true
        # *** 修正点：将 YYYY 改为 yyyy ***
        options: { format: yyyy-MM-dd } 

      - name: author
        label: 作者
        type: select
        options: { values: [ 'Jane Doe', 'John Smith', 'Pages CMS Team' ] }

      - name: body
        label: 文章内容
        type: rich-text 
        
      - name: seo
        label: SEO
        component: seo

  # ----------------------------------------
  # 2. 文件：关于页面 (About Page) (保持不变)
  # ----------------------------------------
  - name: about_page
    label: 关于我们页面
    type: file
    path: src/about.md
    
    fields:
      - name: title
        label: 页面标题
        type: string
        required: true
        
      - name: body
        label: 页面主体
        type: rich-text
        
      - name: primary_ctas
        label: 主要行动按钮
        type: object
        component: cta_button
        list: 
          min: 1
          max: 3
          collapsible: true
          summary: "{fields.text}"
          
      - name: seo
        label: SEO
        component: seo
        
# ====================================================================
# SETTINGS: 全局行为设置 (保持不变)
# ====================================================================
settings:
  hide: false 
  content:
    merge: true