# Pages CMS 配置文件 - 定义内容编辑结构
# ----------------------------------------------------

# 媒体配置：定义文件上传的位置
media:
  # 媒体文件的存储路径（相对于仓库根目录）
  input: src/media
  # 媒体文件在前端网站中的访问路径
  output: /media

# 内容配置：定义可编辑的内容类型（集合和文件）
content:
  # ----------------------------------------
  # 1. 集合：文档 (docs)
  # ----------------------------------------
  - name: docs
    label: Documentation
    type: collection
    # 文档文件的存储路径
    path: src/docs
    # 文档文件的命名模板。{primary} 会被 primary 字段（即 title）的值替代。
    filename: "{primary}.md"
    
    # CMS 界面显示配置
    view:
      # 在列表视图中显示的字段
      fields: [ title, order ]
      # 用作主要标识符的字段（影响文件名和 URL slug）
      primary: title
      # 默认排序规则
      sort: [ order, title ]
      
    # 默认值（通常用于列表排序）
    default:
      sort: order
      order: asc
      
    # 集合中的字段定义
    fields:
      - name: title
        label: Title
        type: string
        required: true
        
      - name: description
        label: Description
        type: string
        options: { maxlength: 180 }
        
      - name: order
        label: Order
        type: number
        
      - name: body
        label: Body
        type: rich-text # 用于 Markdown 或 HTML 内容

  # ----------------------------------------
  # 2. 文件：主页 (homepage)
  # ----------------------------------------
  - label: Home page
    # 单个内容文件的存储路径
    path: src/index.njk
    name: homepage
    type: file
    
    # 文件中的字段定义
    fields:
      - name: layout
        type: string
        hidden: true # 隐藏字段，用户无需编辑
        default: layouts/base.njk
        
      # 组合字段 1: Promotion（对象类型）
      - name: Promotion
        label: Promotion
        type: object
        fields:
          - name: text
            label: Text
            type: string
            
          - name: url
            label: URL
            type: string
            
      # 组合字段 2: Features（对象类型）
      - name: features
        label: Features
        # 注意：图片中 features 字段没有子字段定义，
        # 实际使用时可能是一个 array 或 object，这里假设是 object。
        type: object
        fields:
          # (这里需要添加 Features 的子字段定义，例如：)
          - name: icon
            label: Icon
            type: string
            
          - name: title
            label: Title
            type: string
            required: true
            
          - name: description
            label: Description
            type: string