# .pages.yml - 完整配置示例
# Pages CMS 配置文件

# 媒体文件配置
media:
  - name: images
    label: 图片
    input: src/images
    output: /images
    categories: [image]
    path: images/
  - name: documents
    label: 文档
    input: src/files
    output: /files
    categories: [document]
  - name: assets
    label: 资源文件
    input: public/assets
    output: /assets
    extensions: [svg, ico, webp, avif]

# 可重用的组件定义
components:
  # SEO组件
  seo:
    label: SEO设置
    type: object
    fields:
      - name: title
        label: SEO标题
        type: text
        description: 用于搜索引擎显示的标题
      - name: description
        label: 描述
        type: text
        description: 页面描述，用于搜索引擎和社交媒体分享
      - name: keywords
        label: 关键词
        type: string
        list: true
        description: 用逗号分隔的关键词列表
      - name: og_image
        label: 社交媒体图片
        type: image
        description: 在社交媒体分享时显示的图片

  # 作者信息组件
  author:
    label: 作者信息
    type: object
    fields:
      - name: name
        label: 姓名
        type: string
        required: true
      - name: email
        label: 邮箱
        type: string
        pattern:
          regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          message: '请输入有效的邮箱地址'
      - name: bio
        label: 个人简介
        type: text
      - name: avatar
        label: 头像
        type: image

  # 英雄区域组件
  hero:
    label: 英雄区域
    type: object
    fields:
      - name: title
        label: 主标题
        type: text
        required: true
      - name: subtitle
        label: 副标题
        type: text
      - name: background
        label: 背景图片
        type: image
      - name: cta_text
        label: 行动号召文字
        type: string
      - name: cta_link
        label: 行动号召链接
        type: string

# 内容配置
content:
  # 博客文章集合
  - name: posts
    label: 博客文章
    type: collection
    path: src/content/posts
    format: yaml-frontmatter
    filename: '{year}-{month}-{day}-{slug}.md'
    subfolders: false
    
    # 视图配置
    view:
      layout: list
      fields: [title, date, published, author.name, categories]
      primary: title
      sort: [date, title]
      search: [title, description, body]
      default:
        search: ''
        sort: date
        order: desc
    
    # 字段定义
    fields:
      - name: title
        label: 标题
        type: text
        required: true
        pattern: 
          regex: '^.{10,100}$'
          message: '标题长度应在10-100个字符之间'
      
      - name: slug
        label: URL别名
        type: string
        required: true
        pattern: 
          regex: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
          message: '只能使用小写字母、数字和连字符'
      
      - name: date
        label: 发布日期
        type: date
        required: true
        default: 'now'
      
      - name: updated
        label: 更新日期
        type: date
      
      - name: published
        label: 发布状态
        type: boolean
        default: false
      
      - name: featured
        label: 精选文章
        type: boolean
        default: false
      
      - name: categories
        label: 分类
        type: string
        list:
          min: 1
          max: 3
          collapsible: false
        options:
          suggestions: [技术, 设计, 产品, 市场, 运营, 生活]
      
      - name: tags
        label: 标签
        type: string
        list: true
        options:
          suggestions: [JavaScript, React, Vue, CSS, 性能优化, 用户体验]
      
      - component: seo
      
      - name: cover
        label: 封面图片
        type: image
      
      - name: excerpt
        label: 摘要
        type: text
        description: '文章摘要，用于列表页显示'
      
      - name: author
        component: author
      
      - name: body
        label: 正文内容
        type: rich-text
        required: true

  # 页面集合
  - name: pages
    label: 页面
    type: collection
    path: src/content/pages
    format: yaml-frontmatter
    filename: '{slug}.md'
    
    view:
      layout: tree
      node:
        filename: index.md
        hideDirs: nodes
      fields: [title, path, published]
      primary: title
      sort: [title]
    
    fields:
      - name: title
        label: 页面标题
        type: text
        required: true
      
      - name: path
        label: 页面路径
        type: string
        required: true
        pattern: 
          regex: '^\/[a-z0-9\/-]*$'
          message: '路径必须以斜杠开头，只能包含小写字母、数字、连字符和斜杠'
      
      - name: published
        label: 发布状态
        type: boolean
        default: true
      
      - component: seo
      
      - name: hero
        component: hero
      
      - name: sections
        label: 内容区块
        type: object
        list:
          collapsible:
            collapsed: false
            summary: "{type} - {title}"
        fields:
          - name: type
            label: 区块类型
            type: select
            required: true
            options:
              values:
                text: 文本区块
                image: 图片区块
                cards: 卡片区块
                cta: 行动号召
          
          - name: title
            label: 区块标题
            type: string
          
          - name: content
            label: 内容
            type: rich-text
          
          - name: image
            label: 图片
            type: image
          
          - name: buttons
            label: 按钮
            type: object
            list: true
            fields:
              - name: text
                label: 按钮文字
                type: string
              - name: link
                label: 链接
                type: string
      
      - name: body
        label: 页面内容
        type: rich-text

  # 产品集合
  - name: products
    label: 产品
    type: collection
    path: src/content/products
    format: yaml-frontmatter
    
    view:
      fields: [name, price, category, featured, published]
      primary: name
      sort: [price, name]
      search: [name, description, features]
      default:
        sort: name
        order: asc
    
    fields:
      - name: name
        label: 产品名称
        type: text
        required: true
      
      - name: slug
        label: URL别名
        type: string
        required: true
      
      - name: description
        label: 产品描述
        type: text
        required: true
      
      - name: price
        label: 价格
        type: number
        required: true
      
      - name: compare_price
        label: 原价
        type: number
      
      - name: category
        label: 产品分类
        type: select
        required: true
        options:
          values:
            electronics: 电子产品
            clothing: 服装
            books: 图书
            home: 家居用品
      
      - name: featured
        label: 推荐产品
        type: boolean
        default: false
      
      - name: published
        label: 上架状态
        type: boolean
        default: true
      
      - name: images
        label: 产品图片
        type: image
        list:
          min: 1
          max: 5
      
      - name: features
        label: 产品特性
        type: string
        list: true
      
      - name: specifications
        label: 规格参数
        type: object
        list:
          collapsible: true
        fields:
          - name: key
            label: 参数名
            type: string
          - name: value
            label: 参数值
            type: string
      
      - component: seo

  # 网站配置（单文件）
  - name: site_config
    label: 网站配置
    type: file
    path: src/data/site.yaml
    format: yaml
    
    fields:
      - name: site
        label: 网站信息
        type: object
        fields:
          - name: title
            label: 网站标题
            type: string
            required: true
          - name: description
            label: 网站描述
            type: text
          - name: logo
            label: 网站Logo
            type: image
          - name: favicon
            label: 网站图标
            type: image
      
      - name: social
        label: 社交媒体
        type: object
        list: true
        fields:
          - name: platform
            label: 平台
            type: select
            options:
              values:
                twitter: Twitter
                facebook: Facebook
                instagram: Instagram
                linkedin: LinkedIn
                github: GitHub
          - name: url
            label: 链接
            type: string
      
      - name: contact
        label: 联系信息
        type: object
        fields:
          - name: email
            label: 邮箱
            type: string
          - name: phone
            label: 电话
            type: string
          - name: address
            label: 地址
            type: text

  # 导航菜单配置
  - name: navigation
    label: 导航菜单
    type: file
    path: src/data/navigation.yaml
    format: yaml
    
    fields:
      - name: header
        label: 顶部导航
        type: object
        list: true
        fields:
          - name: label
            label: 菜单文字
            type: string
            required: true
          - name: url
            label: 链接地址
            type: string
            required: true
          - name: children
            label: 子菜单
            type: object
            list: true
            fields:
              - name: label
                label: 子菜单文字
                type: string
              - name: url
                label: 子菜单链接
                type: string
      
      - name: footer
        label: 底部导航
        type: object
        list: true
        fields:
          - name: section
            label: 区块标题
            type: string
          - name: links
            label: 链接列表
            type: object
            list: true
            fields:
              - name: label
                label: 链接文字
                type: string
              - name: url
                label: 链接地址
                type: string

# 全局设置
settings:
  hide: false
  content:
    merge: true