# .pages.yml - 修正完整版
# Pages CMS 配置文件

# 媒体文件配置
media:
  - name: images
    label: Images
    input: images
    output: /images
    categories: [image]
  - name: documents
    label: Documents
    input: files
    output: /files
    categories: [document]

# 可重用的组件定义
components:
  # SEO组件
  seo:
    label: SEO Settings
    type: object
    fields:
      - name: meta_title
        label: Meta Title
        type: text
        description: Title for search engines
      - name: meta_description
        label: Meta Description
        type: text
        description: Description for search engines and social sharing
      - name: og_image
        label: Social Media Image
        type: image
        description: Image displayed when sharing on social media

  # 作者信息组件
  author:
    label: Author Information
    type: object
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: email
        label: Email
        type: string
      - name: avatar
        label: Avatar
        type: image

# 内容配置
content:
  # 博客文章集合 - 简化版本确保工作
  - name: posts
    label: Blog Posts
    type: collection
    path: content/posts
    format: yaml-frontmatter
    filename: '{slug}.md'
    
    # 视图配置
    view:
      layout: list
      fields: [title, date, published]
      primary: title
      sort: [date]
      default:
        sort: date
        order: desc
    
    # 字段定义 - 确保所有必需字段都有
    fields:
      - name: title
        label: Title
        type: text
        required: true
      
      - name: slug
        label: Slug
        type: string
        required: true
      
      - name: date
        label: Date
        type: date
        required: true
        default: 'now'
      
      - name: published
        label: Published
        type: boolean
        default: false
      
      - name: excerpt
        label: Excerpt
        type: text
        description: 'Short description for listing pages'
      
      - name: body
        label: Content
        type: rich-text
        required: true

  # 页面集合
  - name: pages
    label: Pages
    type: collection
    path: content/pages
    format: yaml-frontmatter
    filename: '{slug}.md'
    
    view:
      layout: list
      fields: [title, path, published]
      primary: title
      sort: [title]
    
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      
      - name: slug
        label: Slug
        type: string
        required: true
      
      - name: published
        label: Published
        type: boolean
        default: true
      
      - name: body
        label: Page Content
        type: rich-text

  # 网站配置
  - name: site
    label: Site Configuration
    type: file
    path: data/site.yaml
    format: yaml
    
    fields:
      - name: title
        label: Site Title
        type: string
        required: true
      
      - name: description
        label: Site Description
        type: text
      
      - name: logo
        label: Logo
        type: image

# 全局设置
settings:
  hide: false
  content:
    merge: true