# .pages.yml - 中文完整版
# Pages CMS 配置文件

# 媒体文件配置
media:
  - name: images
    label: 图片库
    input: images
    output: /images
    categories: [image]
  - name: documents
    label: 文档库
    input: files
    output: /files
    categories: [document]

# 可重用的组件定义
components:
  # SEO组件
  seo:
    label: SEO设置
    type: object
    fields:
      - name: meta_title
        label: Meta标题
        type: text
        description: 用于搜索引擎显示的标题
      - name: meta_description
        label: Meta描述
        type: text
        description: 用于搜索引擎和社交媒体分享的描述
      - name: og_image
        label: 社交媒体图片
        type: image
        description: 在社交媒体分享时显示的图片

  # 作者信息组件
  author:
    label: 作者信息
    type: object
    fields:
      - name: name
        label: 姓名
        type: string
        required: true
      - name: email
        label: 邮箱
        type: string
      - name: avatar
        label: 头像
        type: image

# 内容配置
content:
  # 博客文章集合
  - name: posts
    label: 博客文章
    type: collection
    path: content/posts
    format: yaml-frontmatter
    filename: '{slug}.md'
    
    # 视图配置
    view:
      layout: list
      fields: [title, date, published]
      primary: title
      sort: [date]
      default:
        sort: date
        order: desc
    
    # 字段定义
    fields:
      - name: title
        label: 文章标题
        type: text
        required: true
      
      - name: slug
        label: URL别名
        type: string
        required: true
      
      - name: date
        label: 发布日期
        type: date
        required: true
        default: 'now'
      
      - name: published
        label: 发布状态
        type: boolean
        default: false
      
      - name: excerpt
        label: 文章摘要
        type: text
        description: '简短的文章摘要，用于列表页显示'
      
      - name: body
        label: 正文内容
        type: rich-text
        required: true

  # 页面集合
  - name: pages
    label: 页面管理
    type: collection
    path: content/pages
    format: yaml-frontmatter
    filename: '{slug}.md'
    
    view:
      layout: list
      fields: [title, published]
      primary: title
      sort: [title]
    
    fields:
      - name: title
        label: 页面标题
        type: text
        required: true
      
      - name: slug
        label: URL别名
        type: string
        required: true
      
      - name: published
        label: 发布状态
        type: boolean
        default: true
      
      - name: body
        label: 页面内容
        type: rich-text

  # 网站配置
  - name: site
    label: 网站配置
    type: file
    path: data/site.yaml
    format: yaml
    
    fields:
      - name: title
        label: 网站标题
        type: string
        required: true
      
      - name: description
        label: 网站描述
        type: text
      
      - name: logo
        label: 网站Logo
        type: image

# 全局设置
settings:
  hide: false
  content:
    merge: true