# Pages CMS 配置文件
# 适用于中文内容网站/博客

# 媒体配置 - 支持多种媒体类型和文件夹
media:
  - name: images
    label: 图片
    input: public/images
    output: /images
    path: uploads
    extensions: [jpg, jpeg, png, gif, svg, webp, ico]
    categories: [image]
  
  - name: documents
    label: 文档
    input: public/documents
    output: /documents
    extensions: [pdf, doc, docx, xls, xlsx, ppt, pptx]
    categories: [document]
  
  - name: videos
    label: 视频
    input: public/videos
    output: /videos
    extensions: [mp4, avi, mov, webm]
    categories: [video]

# 可复用组件定义
components:
  # SEO 元数据组件
  seo:
    label: SEO 设置
    type: object
    fields:
      - name: title
        label: SEO 标题
        type: string
        description: 在搜索结果中显示的标题（建议 50-60 字符）
        pattern:
          regex: '^.{0,60}$'
          message: SEO 标题应在 60 个字符以内
      
      - name: description
        label: SEO 描述
        type: text
        description: 在搜索结果中显示的描述（建议 120-160 字符）
        pattern:
          regex: '^.{0,160}$'
          message: SEO 描述应在 160 个字符以内
      
      - name: keywords
        label: 关键词
        type: string
        list:
          min: 0
          max: 10
          default: []
        description: 用逗号分隔的关键词列表
      
      - name: ogImage
        label: 社交媒体图片
        type: image
        description: 在社交媒体分享时显示的图片（建议尺寸：1200x630px）

  # 作者信息组件
  author:
    label: 作者信息
    type: object
    fields:
      - name: name
        label: 姓名
        type: string
        required: true
      
      - name: email
        label: 邮箱
        type: string
        pattern:
          regex: '^([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})?$'
          message: 请输入有效的邮箱地址（例如：hello@example.com）
      
      - name: avatar
        label: 头像
        type: image
      
      - name: bio
        label: 简介
        type: text
        description: 作者的简短介绍

  # 联系方式组件
  contact:
    label: 联系方式
    type: object
    fields:
      - name: phone
        label: 电话
        type: string
        pattern:
          regex: '^(1[3-9]\d{9})?$'
          message: 请输入有效的手机号码（可选）
      
      - name: email
        label: 邮箱
        type: string
        pattern:
          regex: '^([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})?$'
          message: 请输入有效的邮箱地址（可选）
      
      - name: wechat
        label: 微信
        type: string
      
      - name: address
        label: 地址
        type: text

# 内容配置
content:
  # 博客文章集合
  - name: posts
    label: 博客文章
    type: collection
    path: content/posts
    format: yaml-frontmatter
    filename: '{year}-{month}-{day}-{primary}'
    exclude: [README.md, .DS_Store]
    subfolders: true
    view:
      layout: list
      fields: [title, date, status, category, author.name, tags]
      primary: title
      sort: [date, title, status]
      search: [title, summary, tags, category, author.name]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: 标题
        type: string
        required: true
        description: 文章的主标题
      
      - name: slug
        label: URL 别名
        type: string
        pattern:
          regex: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
          message: URL 别名只能包含小写字母、数字和连字符
        description: 用于生成文章 URL 的唯一标识符
      
      - name: date
        label: 发布日期
        type: date
        required: true
        default: '{now}'
      
      - name: updated
        label: 更新日期
        type: date
      
      - name: status
        label: 状态
        type: select
        required: true
        default: draft
        options:
          choices:
            - value: draft
              label: 草稿
            - value: published
              label: 已发布
            - value: archived
              label: 已归档
      
      - name: featured
        label: 置顶文章
        type: boolean
        default: false
        description: 是否在首页置顶显示
      
      - name: category
        label: 分类
        type: select
        required: true
        default: other
        options:
          choices:
            - value: tech
              label: 技术
            - value: life
              label: 生活
            - value: travel
              label: 旅行
            - value: food
              label: 美食
            - value: reading
              label: 阅读
            - value: other
              label: 其他
      
      - name: tags
        label: 标签
        type: string
        list:
          min: 0
          max: 5
          default: []
          collapsible: false
        description: 为文章添加标签（最多5个）
      
      - name: summary
        label: 摘要
        type: text
        description: 文章的简短描述，将显示在列表页
      
      - name: cover
        label: 封面图片
        type: image
        description: 文章的封面图片（建议尺寸：1920x1080px）
      
      - name: author
        label: 作者
        type: object
        default:
          name: 匿名作者
        fields:
          - name: name
            label: 姓名
            type: string
            default: 匿名作者
          
          - name: email
            label: 邮箱
            type: string
          
          - name: avatar
            label: 头像
            type: image
          
          - name: bio
            label: 简介
            type: text
      
      - name: seo
        label: SEO 设置
        component: seo
      
      - name: toc
        label: 显示目录
        type: boolean
        default: true
        description: 是否显示文章目录
      
      - name: comments
        label: 允许评论
        type: boolean
        default: true
        description: 是否允许读者评论
      
      - name: body
        label: 正文内容
        type: rich-text
        required: true

  # 页面集合
  - name: pages
    label: 独立页面
    type: collection
    path: content/pages
    format: yaml-frontmatter
    filename: '{primary}'
    view:
      fields: [title, slug, updated, status]
      primary: title
      sort: [title, updated]
      default:
        sort: updated
        order: desc
    fields:
      - name: title
        label: 页面标题
        type: string
        required: true
      
      - name: slug
        label: URL 别名
        type: string
        required: true
        pattern:
          regex: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
          message: URL 别名只能包含小写字母、数字和连字符
      
      - name: status
        label: 状态
        type: select
        default: draft
        options:
          choices:
            - value: draft
              label: 草稿
            - value: published
              label: 已发布
      
      - name: updated
        label: 更新日期
        type: date
        default: '{now}'
      
      - name: template
        label: 页面模板
        type: select
        default: default
        options:
          choices:
            - value: default
              label: 默认模板
            - value: fullwidth
              label: 全宽模板
            - value: sidebar
              label: 侧边栏模板
            - value: landing
              label: 着陆页模板
      
      - name: seo
        label: SEO 设置
        component: seo
      
      - name: body
        label: 页面内容
        type: rich-text

  # 团队成员集合
  - name: team
    label: 团队成员
    type: collection
    path: content/team
    format: yaml-frontmatter
    filename: '{primary}'
    view:
      fields: [name, position, department, joinDate, status]
      primary: name
      sort: [joinDate, name]
      default:
        sort: joinDate
        order: desc
    fields:
      - name: name
        label: 姓名
        type: string
        required: true
      
      - name: position
        label: 职位
        type: string
        required: true
      
      - name: department
        label: 部门
        type: select
        default: development
        options:
          choices:
            - value: management
              label: 管理层
            - value: development
              label: 研发部
            - value: design
              label: 设计部
            - value: marketing
              label: 市场部
            - value: sales
              label: 销售部
            - value: hr
              label: 人力资源部
      
      - name: joinDate
        label: 入职日期
        type: date
        default: '{now}'
      
      - name: status
        label: 状态
        type: select
        default: active
        options:
          choices:
            - value: active
              label: 在职
            - value: inactive
              label: 离职
      
      - name: avatar
        label: 头像
        type: image
        description: 建议尺寸：400x400px
      
      - name: bio
        label: 个人简介
        type: text
      
      - name: contact
        label: 联系方式
        component: contact
      
      - name: social
        label: 社交媒体
        type: object
        fields:
          - name: github
            label: GitHub
            type: string
          
          - name: linkedin
            label: LinkedIn
            type: string
          
          - name: twitter
            label: Twitter
            type: string
          
          - name: website
            label: 个人网站
            type: string
            pattern:
              regex: '^(https?:\/\/.+)?$'
              message: 请输入有效的网址（以 http:// 或 https:// 开头）

  # 网站配置（单文件）
  - name: siteConfig
    label: 网站配置
    type: file
    path: content/config/site.yml
    format: yaml
    fields:
      - name: site
        label: 网站信息
        type: object
        default:
          title: 我的网站
          description: 欢迎访问我的网站
          keywords: []
          language: zh-CN
        fields:
          - name: title
            label: 网站标题
            type: string
            default: 我的网站
            required: true
          
          - name: description
            label: 网站描述
            type: text
            default: 欢迎访问我的网站
            required: true
          
          - name: keywords
            label: 默认关键词
            type: string
            list:
              min: 0
              max: 10
              default: []
          
          - name: logo
            label: 网站 Logo
            type: image
          
          - name: favicon
            label: 网站图标
            type: image
          
          - name: language
            label: 默认语言
            type: select
            default: zh-CN
            options:
              choices:
                - value: zh-CN
                  label: 简体中文
                - value: zh-TW
                  label: 繁体中文
                - value: en-US
                  label: 英语（美国）
                - value: ja-JP
                  label: 日语
      
      - name: contact
        label: 联系信息
        type: object
        default: {}
        fields:
          - name: phone
            label: 电话
            type: string
            description: 可选，留空即可
          
          - name: email
            label: 邮箱
            type: string
            pattern:
              regex: '^([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})?$'
              message: 请输入有效的邮箱地址（可选）
            description: 可选，留空即可
          
          - name: wechat
            label: 微信
            type: string
          
          - name: address
            label: 地址
            type: text
      
      - name: social
        label: 社交媒体
        type: object
        default: {}
        fields:
          - name: wechat
            label: 微信公众号
            type: string
          
          - name: weibo
            label: 微博
            type: string
          
          - name: douyin
            label: 抖音
            type: string
          
          - name: bilibili
            label: B站
            type: string
          
          - name: github
            label: GitHub
            type: string
          
          - name: twitter
            label: Twitter
            type: string
      
      - name: analytics
        label: 分析工具
        type: object
        default: {}
        fields:
          - name: baiduAnalytics
            label: 百度统计 ID
            type: string
          
          - name: googleAnalytics
            label: Google Analytics ID
            type: string
            pattern:
              regex: '^(UA-\d{4,10}-\d{1,4}|G-[A-Z0-9]+)?$'
              message: 请输入有效的 Google Analytics ID（可选）
      
      - name: features
        label: 功能开关
        type: object
        default:
          darkMode: true
          search: true
          comments: true
          newsletter: false
        fields:
          - name: darkMode
            label: 深色模式
            type: boolean
            default: true
          
          - name: search
            label: 站内搜索
            type: boolean
            default: true
          
          - name: comments
            label: 评论系统
            type: boolean
            default: true
          
          - name: newsletter
            label: 邮件订阅
            type: boolean
            default: false

  # 导航菜单（单文件）
  - name: navigation
    label: 导航菜单
    type: file
    path: content/config/navigation.yml
    format: yaml
    fields:
      - name: mainMenu
        label: 主菜单
        type: object
        list:
          min: 0
          max: 10
          default:
            - label: 首页
              url: /
              target: _self
            - label: 博客
              url: /blog
              target: _self
            - label: 关于
              url: /about
              target: _self
          collapsible:
            collapsed: false
            summary: "{label} ({url})"
        fields:
          - name: label
            label: 菜单标签
            type: string
            required: true
            default: 新菜单
          
          - name: url
            label: 链接地址
            type: string
            required: true
            default: /
          
          - name: target
            label: 打开方式
            type: select
            default: _self
            options:
              choices:
                - value: _self
                  label: 当前窗口
                - value: _blank
                  label: 新窗口
          
          - name: icon
            label: 图标
            type: string
            description: 图标类名或 SVG 路径
          
          - name: children
            label: 子菜单
            type: object
            list:
              min: 0
              max: 10
              default: []
            fields:
              - name: label
                label: 子菜单标签
                type: string
                required: true
                default: 子菜单
              
              - name: url
                label: 链接地址
                type: string
                required: true
                default: /
              
              - name: description
                label: 描述
                type: string
      
      - name: footerMenu
        label: 页脚菜单
        type: object
        list:
          min: 0
          max: 4
          default:
            - title: 关于我们
              links:
                - label: 公司介绍
                  url: /about
                - label: 联系我们
                  url: /contact
            - title: 服务
              links:
                - label: 产品
                  url: /products
                - label: 定价
                  url: /pricing
          collapsible:
            collapsed: true
            summary: "{title}"
        fields:
          - name: title
            label: 栏目标题
            type: string
            required: true
            default: 新栏目
          
          - name: links
            label: 链接列表
            type: object
            list:
              min: 0
              max: 10
              default:
                - label: 链接
                  url: /
            fields:
              - name: label
                label: 链接文本
                type: string
                required: true
                default: 新链接
              
              - name: url
                label: 链接地址
                type: string
                required: true
                default: /

# 全局设置
settings:
  hide: false
  content:
    merge: true